name: Linting 📑🔎⚡

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff ⚡🕵

    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: Run Ruff checks ⚡
        uses: astral-sh/ruff-action@v3
        with:
          args: check

  markdownlint:
    name: Markdownlint 📑🕵

    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2-action 📑
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: |
            *.md
            !test/*.md
